---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      network:
        - ["forwarded_port", { guest: 80, host: 8080 }]
        - ["private_network", { ip: "192.168.33.33" }]

suites:
  - name: default
    run_list:
      - recipe[LEMPChefCookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
