---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      network:
        - ['forwarded_port', { guest: 80, host: 8080 }]
        - ['private_network', { ip: '104.131.61.222' }]

suites:
  - name: default
    data_bags_path: 'data_bags'
    encrypted_data_bag_secret_key_path: '~/.chef/encrypted_data_bag_secret'
    run_list:
      - recipe[acme_server::default]
      # - recipe[LEMPChefCookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      acme:
        contact: mailto:admin@example.com
        endpoint: http://127.0.0.1:4000
      # boulder:
      #   revision: 2d33a9900cafe82993744fe73bd341fe47df2171
      nginx:
        server_names_hash_bucket_size: 256