rvm:
  - 2.3

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

branches:
  only:
    - master

before_script:
  - cookstyle --version
  - foodcritic --version

script:
  - cookstyle
  - foodcritic .
  - chef exec rspec

notifications:
  email: false